// --- CLASS 11th & 12th CBSE BLUEPRINTS REPOSITORY ---
export const BLUEPRINTS_11_12 = {
  "History": { maxMarks: 80, totalQuestions: 34, sections: ["Section A", "Section B", "Section C", "Section D", "Section E"] },
  "Geography": { maxMarks: 70, totalQuestions: 30, sections: ["Section A", "Section B", "Section C", "Section D", "Section E"] },
  "Political Science": { maxMarks: 80, totalQuestions: 30, sections: ["Section A", "Section B", "Section C", "Section D", "Section E"] },
  "Physics": { maxMarks: 70, totalQuestions: 33, sections: ["Section A", "Section B", "Section C", "Section D", "Section E"] },
  "Chemistry": { maxMarks: 70, totalQuestions: 33, sections: ["Section A", "Section B", "Section C", "Section D", "Section E"] },
  "Biology": { maxMarks: 70, totalQuestions: 33, sections: ["Section A", "Section B", "Section C", "Section D", "Section E"] },
  "Mathematics": { maxMarks: 80, totalQuestions: 38, sections: ["Section A", "Section B", "Section C", "Section D", "Section E"] },
  "Applied Mathematics": { maxMarks: 80, totalQuestions: 38, sections: ["Section A", "Section B", "Section C", "Section D", "Section E"] },
  "Psychology": { maxMarks: 70, totalQuestions: 33, sections: ["Section A", "Section B", "Section C", "Section D", "Section E", "Section F"] },
  "Home Science": { maxMarks: 70, totalQuestions: 35, sections: ["Section A", "Section B", "Section C", "Section D"] },
  "Informatics Practices": { maxMarks: 70, totalQuestions: 37, sections: ["Section A", "Section B", "Section C", "Section D", "Section E"] },
  "Computer Science": { maxMarks: 70, totalQuestions: 37, sections: ["Section A", "Section B", "Section C", "Section D", "Section E"] },
  "Legal Studies": { maxMarks: 80, totalQuestions: 40, sections: ["Section A", "Section B", "Section C", "Section D"] },
  "Business Studies": { maxMarks: 80, totalQuestions: 34, sections: ["Section A", "Section B", "Section C", "Section D"] },
  "Economics": { maxMarks: 80, totalQuestions: 34, sections: ["Section A", "Section B"] },
  "Accountancy": { maxMarks: 80, totalQuestions: 34, sections: ["Part A", "Part B"] },
  "Hindi Core": { maxMarks: 80, totalQuestions: 12, sections: ["Khand K", "Khand Kh", "Khand G"] },
  "Hindi Elective": { maxMarks: 80, totalQuestions: 13, sections: ["Khand K", "Khand Kh", "Khand G"] },
  "English Core": { maxMarks: 80, totalQuestions: 13, sections: ["Section A", "Section B", "Section C"] },
  "English Elective": { maxMarks: 80, totalQuestions: 13, sections: ["Section A", "Section B", "Section C"] },
  "NCC": { maxMarks: 70, totalQuestions: 21, sections: ["Section A", "Section B", "Section C", "Section D", "Section E", "Section F"] },
  "Physical Education": { maxMarks: 70, totalQuestions: 37, sections: ["Section A", "Section B", "Section C", "Section D", "Section E"] },
  "Urdu Core": { maxMarks: 80, totalQuestions: 11, sections: ["Section A", "Section B"] },
  "Urdu Elective": { maxMarks: 80, totalQuestions: 11, sections: ["Section A", "Section B"] },
  "Sanskrit Elective": { maxMarks: 80, totalQuestions: 19, sections: ["Khand Ka", "Khand Kha", "Khand Ga", "Khand Gha", "Khand Nga"] },
  "Sanskrit Core": { maxMarks: 80, totalQuestions: 18, sections: ["Khand Ka", "Khand Kha", "Khand Ga", "Khand Gha"] }
};
