export const ROLES = {
  DEVELOPER: 'DEVELOPER',              // Super SaaS Admin
  DIRECTOR: 'DIRECTOR',                // School Management
  PRINCIPAL: 'PRINCIPAL',              // School Head
  VICE_PRINCIPAL: 'VICE_PRINCIPAL',    // Academic Head / Coordinator
  TEACHER: 'TEACHER'                   // Subject Faculty
};

// Hierarchy Weight (Higher value = Higher authority)
export const HIERARCHY_RANK = {
  DEVELOPER: 100,
  DIRECTOR: 80,
  PRINCIPAL: 60,
  VICE_PRINCIPAL: 40,
  TEACHER: 20
};

// Kis role ko kya karne ki permission hai
export const PERMISSIONS = {
  CAN_VIEW_ALL_SCHOOLS: [ROLES.DEVELOPER],
  CAN_MANAGE_PAYMENTS: [ROLES.DEVELOPER, ROLES.DIRECTOR, ROLES.PRINCIPAL],
  CAN_GENERATE_INVITE_CODE: [ROLES.DEVELOPER, ROLES.DIRECTOR, ROLES.PRINCIPAL, ROLES.VICE_PRINCIPAL],
  CAN_SUSPEND_USERS: [ROLES.DEVELOPER, ROLES.DIRECTOR, ROLES.PRINCIPAL, ROLES.VICE_PRINCIPAL],
  CAN_CREATE_PAPERS: [ROLES.DEVELOPER, ROLES.DIRECTOR, ROLES.PRINCIPAL, ROLES.VICE_PRINCIPAL, ROLES.TEACHER],
  CAN_VIVA_PRACTICAL: [ROLES.DEVELOPER, ROLES.DIRECTOR, ROLES.PRINCIPAL, ROLES.VICE_PRINCIPAL, ROLES.TEACHER]
};
